Opis git blame -C
bikol/DINO201920 pull request #10
Opened 2019-10-30 17:31 UTC by devid2971

2019-11-04 09:53 UTC, bikol requested changes
Proszę zrobić merge z masterem

2019-11-04 18:16 UTC, devid2971 commented
Mam nadzieję, że się udało

2019-11-05 09:15 UTC, bikol requested changes
Udało się, ale niestety ktoś znów był pierwszy

2019-11-05 17:41 UTC, devid2971 commented
Może teraz się uda

2019-11-13 12:59 UTC, merged